// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF2AXPyOL1rT8hqyzpEVtLqiF4a-Tskk4',
    appId: '1:348826671507:web:5b74998297ff0a88c67066',
    messagingSenderId: '348826671507',
    projectId: 'lifentech-a3928',
    authDomain: 'lifentech-a3928.firebaseapp.com',
    databaseURL: 'https://lifentech-a3928-default-rtdb.firebaseio.com',
    storageBucket: 'lifentech-a3928.appspot.com',
    measurementId: 'G-9GB7PJ9LTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYzhI-WN8jG9Tv7JrgTpt9Mx2OvoBo-hg',
    appId: '1:348826671507:android:2de7c14ca5a79b07c67066',
    messagingSenderId: '348826671507',
    projectId: 'lifentech-a3928',
    databaseURL: 'https://lifentech-a3928-default-rtdb.firebaseio.com',
    storageBucket: 'lifentech-a3928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAecUWcEcUnBPgfSKsgI38vI8F_5pFCfik',
    appId: '1:348826671507:ios:f31587f8ad729ea6c67066',
    messagingSenderId: '348826671507',
    projectId: 'lifentech-a3928',
    databaseURL: 'https://lifentech-a3928-default-rtdb.firebaseio.com',
    storageBucket: 'lifentech-a3928.appspot.com',
    iosBundleId: 'com.example.lft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAecUWcEcUnBPgfSKsgI38vI8F_5pFCfik',
    appId: '1:348826671507:ios:b710dc4028e10b06c67066',
    messagingSenderId: '348826671507',
    projectId: 'lifentech-a3928',
    databaseURL: 'https://lifentech-a3928-default-rtdb.firebaseio.com',
    storageBucket: 'lifentech-a3928.appspot.com',
    iosBundleId: 'com.example.lft.RunnerTests',
  );
}
